AllCops:
  Include:
    - 'lib/unparser.rb'
    - 'lib/unparser/**/*.rb'
    - '**/*.rake'
    - 'Gemfile'
    - 'Gemfile.triage'
  TargetRubyVersion: 3.0
  Exclude:
    - tmp/**/*
    - vendor/**/*
  NewCops: enable

# Avoid parameter lists longer than five parameters.
Metrics/ParameterLists:
  Max: 3
  CountKeywordArgs: true

Metrics/MethodLength:
  CountComments: false
  Max: 17

Metrics/AbcSize:
  Max: 18

# Avoid more than `Max` levels of nesting.
Metrics/BlockNesting:
  Max: 3

# Align with the style guide.
Style/CollectionMethods:
  PreferredMethods:
    collect:  'map'
    inject:   'reduce'
    find:     'detect'
    find_all: 'select'

# Use `fail` as `raise` implies re-raising
Style/SignalException:
  EnforcedStyle: semantic

# Limit line length
Layout/LineLength:
  Max: 113  # TODO: lower to 79 once the rubocop branch in shared/Gemfile is removed

Metrics/ClassLength:
  Max: 205

# Prefer modifiers and explicit if statements over returning early for small methods
Style/GuardClause:
  Enabled: false

Metrics/BlockLength:
  Exclude:
  # Ignore RSpec DSL
  - spec/**/*

# Flags freezes for singletons that could still be mutated like Regexps
Style/RedundantFreeze:
  Enabled: false

# Disabled because of indenting with private keyword in class bodies.
Layout/IndentationWidth:
  Enabled: false

# Disable documentation checking until a class needs to be documented once
Style/Documentation:
  Enabled: false

# Do not favor modifier if/unless usage when you have a single-line body
Style/IfUnlessModifier:
  Enabled: false

# I like to have an empty line before closing the currently opened body
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# I like my style more
Layout/AccessModifierIndentation:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/MixinGrouping:
  Enabled: false

Lint/BooleanSymbol:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Naming/RescuedExceptionsVariableName:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false
