# encoding: UTF-8

module Unparser
  # Preprocessor to normalize AST generated by parser
  class Preprocessor
    include Adamantium::Flat, NodeHelpers, AbstractType, Concord.new(:node), Procto.call(:result)

    # Return preprocessor result
    #
    # @return [Parser::AST::Node]
    #
    # @api private
    #
    abstract_method :result

    EMPTY = Parser::AST::Node.new(:empty)

    # Run preprocessor for node
    #
    # @param [Parser::AST::Node, nil] node
    #
    # @return [Parser::AST::Node, nil]
    #
    # @api private
    #
    def self.run(node)
      return EMPTY if node.nil?
      REGISTRY.fetch(node.type, [Noop]).reduce(node) do |current, processor|
        processor.call(current)
      end
    end

    REGISTRY = Hash.new { |hash, key| hash[key] = [] }

    # Register preprocessor
    #
    # @param [Symbol] type
    #
    # @return [undefined]
    #
    # @api private
    #
    def self.register(type)
      REGISTRY[type] << self
    end
    private_class_method :register

  private

    # Visit node
    #
    # @param [Parser::AST::Node]
    #
    # @return [undefined]
    #
    # @api private
    #
    def visit(node)
      self.class.run(node)
    end

    # Return children
    #
    # @return [Array<Parser::AST::Node>]
    #
    # @api private
    #
    def children
      node.children
    end

    # Return visited children
    #
    # @return [Array<Parser::Ast::Node>]
    #
    # @api private
    #
    def visited_children
      children.map do |node|
        if node.kind_of?(Parser::AST::Node)
          visit(node)
        else
          node
        end
      end
    end

    # Noop preprocessor that just passes through noode.
    class Noop < self

      register :int
      register :str

      # Return preprocessor result
      #
      # @return [Parser::AST::Node]
      #
      # @api private
      #
      def result
        n(node.type, visited_children)
      end

    end # Noop

    # Preprocessor for dynamic string regexp and xtr nodes. Collapses adjacent string segments into one.
    class CollapseStrChildren < self

      register :dstr
      register :regexp
      register :xstr

      # Return preprocessor result
      #
      # @return [Parser::AST::Node]
      #
      # @api private
      #
      def result
        node.updated(nil, collapsed_children)
      end

    private

      # Return collapsed children
      #
      # @return [Array<Parser::AST::Node>]
      #
      # @api private
      #
      def collapsed_children
        chunked_children.each_with_object([]) do |(type, nodes), aggregate|
          if type == :str
            aggregate << s(:str, nodes.map { |node| node.children.first }.join)
          else
            aggregate.concat(nodes)
          end
        end
      end
      memoize :collapsed_children

      # Return chunked children
      #
      # @return [Array<Parser::AST::Node>]
      #
      # @api private
      #
      def chunked_children
        visited_children.chunk(&:type)
      end

    end # CollapseStrChildren

    class CompactDSTR < self

      register :dstr

      # Return preprocessor result
      #
      # @return [Parser::AST::Node]
      #
      # @api private
      #
      def result
        if children.all? { |child| child.type == :str }
          node.updated(:str, [children.map { |child| child.children.first }.join])
        else
          node
        end
      end

    end # CompactDSTR

    class Inifnity < self

      register :float
      register :int

      NEG_INFINITY = Float::INFINITY - 1

      # Return preprocessor result
      #
      # @param [Parser::AST::Node]
      #
      # @api pirvate
      #
      def result
        value = node.children.first
        case value
        when Float::INFINITY
          s(:const, s(:const, nil, :Float), :INFINITY)
        when -NEG_INFINITY
          s(:send, s(:const, s(:const, nil, :Float), :INFINITY), :-@)
        else
          node
        end
      end
    end

    # Preprocessor for begin nodes. Removes begin nodes with one child.
    #
    # These superflownosely currently get generated by unparser.
    #
    class Begin < self

      register :begin

      # Return preprocessor result
      #
      # @return [Parser::AST::Node]
      #
      # @api private
      #
      def result
        if children.one?
          visit(children.first)
        else
          Noop.call(node)
        end
      end

    end # Begin
  end # Preprocessor
end # Unparser
