---
includes:
- lib
integration: rspec
requires:
- unparser
matcher:
  subjects:
  - 'Unparser*'
  ignore:
  - 'Unparser::Builder#initialize'
  - 'Unparser::CLI*'
  - 'Unparser::Concord#define_readers'
  - 'Unparser::Emitter#emit_comments'
  - 'Unparser::Emitter#emit_comments_before'
  - 'Unparser::Emitter#emit_eol_comments'
  - 'Unparser::Emitter.handle'
  - 'Unparser::Emitter::Args#normal_arguments'
  - 'Unparser::Emitter::Args#shadowargs'
  - 'Unparser::Emitter::Array#emitters'
  - 'Unparser::Emitter::Binary#writer'
  - 'Unparser::Emitter::Block#target_writer'
  - 'Unparser::Emitter::BlockPass#dispatch' # 3.1+ specific
  - 'Unparser::Emitter::Class#dispatch'
  - 'Unparser::Emitter::Class#local_variable_scope'
  - 'Unparser::Emitter::Def#local_variable_scope'
  - 'Unparser::Emitter::FindPattern#dispatch' # 3.0+ specific
  - 'Unparser::Emitter::Hash#emit_heredoc_reminder_member' # 3.2+ specific
  - 'Unparser::Emitter::HashPattern#write_symbol_body'
  - 'Unparser::Emitter::LocalVariableRoot*'
  - 'Unparser::Emitter::LocalVariableRoot.included'
  - 'Unparser::Emitter::MatchPattern#dispatch' # 2.7+ specific
  - 'Unparser::Emitter::MatchPatternP#dispatch' # 3.0+ specific
  - 'Unparser::Emitter::MatchRest#dispatch' # 3.0+ specific
  - 'Unparser::Emitter::Module#local_variable_scope'
  - 'Unparser::Emitter::Root#local_variable_scope'
  - 'Unparser::Emitter::Send#writer'
  - 'Unparser::NodeDetails.included'
  - 'Unparser::Validation.from_string'
  - 'Unparser::Validation::Literal*'
  - 'Unparser::Writer.included'
  - 'Unparser::Writer::Binary#left_emitter'
  - 'Unparser::Writer::Binary#right_emitter'
  - 'Unparser::Writer::Send#details'
  - 'Unparser::Writer::Send#effective_writer'
